"""create scan table

Revision ID: 0b4e65bf2208
Revises: 
Create Date: 2026-06-06 21:07:17.248432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4e65bf2208'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('target_url', sa.String(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('completed_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vulnerability',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('scan_id', sa.Integer(), nullable=False),
                    sa.Column('vuln_type', sa.String(), nullable=False),
                    sa.Column('severity', sa.String(), nullable=False),
                    sa.Column('affected_url', sa.String(), nullable=False),
                    sa.Column('parameter', sa.String(), nullable=False),
                    sa.Column('payload', sa.String(), nullable=False),
                    sa.Column('evidence', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('fix', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerability')
    op.drop_table('scan')
    # ### end Alembic commands ###
